# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: decoworship.PulseMeet
PackageVersion: 0.9.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/decoworship/meeting-transcription/releases/download/v0.9.1/PulseMeet-0.9.1-instalador.exe
  InstallerSha256: FC8DD52F45BF1C4F30C0DA403E2B37F286AC68B419EC1618F056D800C490F814
  ProductCode: '{8B6F3A21-4C5E-4E17-9A2D-1F0B7C4E9D33}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: PulseMeet
    Publisher: decoworship
    ProductCode: '{8B6F3A21-4C5E-4E17-9A2D-1F0B7C4E9D33}_is1'
    UpgradeCode: '{8B6F3A21-4C5E-4E17-9A2D-1F0B7C4E9D33}'
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-01
